image: $DOCKER_REGISTRY_PREFIX/2smart/utils/combined-ci-image:buildx

stages:
  - test
  - build
  - release
  - buildx

before_script:
  - git clone https://oauth2:$ACCESS_TOKEN@$DOCKER_UTILS_REPO_URL
  - mv docker-utils/utils.sh docker.sh

services:
  - name: $DOCKER_REGISTRY_PREFIX/2smart/base-images/docker-dind
    alias: docker
    command: [ "--experimental" ]

variables:
  ENV_MODE: 'test'
  IMAGE_PLATFORMS: linux/amd64,linux/arm/v7

lint:
  before_script:
    - npm i
  stage: test
  script:
    - npm run test:lint
  only:
    - 'merge_requests'
    - 'master'

test:
  before_script:
    - npm i
  stage: test
  script:
    - npm run test
  only:
    - 'merge_requests'
    - 'master'

build:
  stage: build
  script:
    - ./docker.sh rundaemon
    - ./docker.sh build
    - ./docker.sh push
    - ./docker.sh push_bridge_type_to_demo
  only:
    - 'master'

release:
  stage: release
  script:
    - ./docker.sh rundaemon
    - ./docker.sh release_bridge_type
  only:
    - 'release'

buildx:
  stage: buildx
  script:
    - ./docker.sh rundaemon
    - ./docker.sh login
    - SOURCE_TAG=$MULTIPLATFORM_TAG ./docker.sh buildx
  when: manual
  allow_failure: true